### ISSUE TITLE
[BUG] Selecting Modes > Time computation > Elapsed since

### ISSUE THREAD

**Issue by Herostere** [groundziro/calculator-cucumber#23]
**Describe the bug**
Not showing a window

**To Reproduce**
Current behaviour on branch Laurent_release

**Expected behavior**
Opening a new window with 
 * a field to select the date
 * a text field to enter the hours
 * a button "elapsed since"

**Comment by Herostere** [comment]
Will never be solved

**Comment by groundziro** [comment]
Menu Added and Functional
